name: ugaoo
description: "A Green E-commerce App"
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.5
  country_flags: ^4.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  shimmer: ^3.0.0
  file_picker: ^10.3.3
  firebase_core: ^4.1.0
  firebase_remote_config: ^6.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_screenutil: ^6.0.0-alpha.1
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  realm: ^20.1.1
  retrofit: ^4.7.2
  shared_preferences: ^2.5.3
  talker: ^5.0.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.7
  json_serializable: ^6.9.5
  very_good_analysis: ^9.0.0


flutter:
  uses-material-design: true

  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf

  assets:
    - assets/data/json/